import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:wallpaper_app/models/catagories_model.dart';
import 'package:wallpaper_app/models/wallpeper_model.dart';
import 'package:wallpaper_app/views/catagoriespage.dart';
import 'package:wallpaper_app/views/image.dart';
import 'package:wallpaper_app/views/widget.dart';
import 'package:http/http.dart' as http;

final apiKey = '563492ad6f91700001000001cad938778c25431d9e4df2c9d7ce39c9';

var scaffoldKey = GlobalKey<ScaffoldState>();

class ScreenHome extends StatelessWidget {

 ScreenHome({Key? key,}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
       key: scaffoldKey,
     drawer: SizedBox(
      width: 230,
      child: Drawer(
        child: SafeArea(child: Column(
          children: [
            SizedBox(height: 10,),
            Text("Categories",style: TextStyle(fontWeight: FontWeight.bold,fontSize: 20),),
            SizedBox(height: 20,),
            Expanded(
              child: ListView.builder(itemCount: categories.length,
                itemBuilder: (context, index) {

                return ListTile(
                  onTap: () {
                    Navigator.of(context).push(MaterialPageRoute(builder: (context) {
                      return Catragorypage(index: index);
                    },));
                  },
                  title: Text(categories[index],style: TextStyle(),),
                );
              },),
            )
          ],
        ),),
      ),
     ),
     
    
      appBar: AppBar(
        title: BarandName(),
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          onPressed: () {
            scaffoldKey.currentState?.openDrawer();
          },icon: Icon(Icons.more_vert,color: Colors.black,),
      ),),
      body: FutureBuilder<List<Photos?>>(
          future: getTrendWalpappers(),
          builder: (context, AsyncSnapshot<List<Photos?>> snaphot) {
            if (snaphot.connectionState == ConnectionState.waiting) {
              return Center(
                child: CircularProgressIndicator(),
              );
            }

            if (snaphot.hasError) {
              return Center(
                child: Text('Something went wrong!!'),
              );
            }

            List<Photos?> photos = snaphot.data!;

            return GridView.builder(
                itemCount: photos.length,
                gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: 3,
                    childAspectRatio: 3 / 5,
                    mainAxisSpacing: 2,
                    crossAxisSpacing: 2),
                itemBuilder: (context, index) {
                  return GestureDetector(
                    onTap: () {
                      Get.to(ImageView(imageviews: photos, initialindex: index));
                    },
                    
                    child: Container(
                     
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image: NetworkImage(photos[index]!.src!.large!),
                          fit: BoxFit.cover
                        ),
                        borderRadius: BorderRadius.circular(10),
                      ),
                    ),
                  );
                });
          }),
    );
  }
}

Future<List<Photos?>> getTrendWalpappers() async {
  final url = Uri.parse(
    'https://api.pexels.com/v1/search?per_page=500&query=bike',
  );

  var response = await http.get(url, headers: {
    "Authorization": apiKey,
  });

  Autogenerated autogenerated =
      Autogenerated.fromJson(jsonDecode(response.body));

  return autogenerated.photos!;
}
